rootfs: rework pci add/remove handling
Emulate minios behavior instead of detecting PCI add/remove events. This
way we get the same timing behavior as with minios stubdoms or qemu in
dom0.

diff --git a/rootfs/init b/rootfs/init
--- a/rootfs/init
+++ b/rootfs/init
@@ -8,10 +8,6 @@ mount -t proc /proc /proc
 
 echo 1 > /proc/sys/vm/overcommit_memory
 
-: > /dev/mdev.seq
-: > /dev/mdev.log
-echo /bin/mdev > /proc/sys/kernel/hotplug
-
 if test -e /sys/class/net/eth0; then
   ip link set eth0 address fe:ff:ff:ff:ff:fe
   ip addr flush eth0
@@ -99,6 +95,91 @@ while true; do
   mv /tmp/qmp/new-res /tmp/qmp/res/$id
 done
 ) >/tmp/qmp/qemu.in </tmp/qmp/qemu.out &
+
+qmp_req() {
+  local id=$(cat /proc/sys/kernel/random/uuid)
+  echo "$1" > /tmp/qmp/new-req_$id
+  mv /tmp/qmp/new-req_$id /tmp/qmp/req/$id
+  while ! [ -f /tmp/qmp/res/$id ]; do sleep 0.1; done
+  cat /tmp/qmp/res/$id
+  rm /tmp/qmp/res/$id
+}
+
+(
+target="$(xenstore-read target)"
+device_model="device-model/$target"
+
+while true; do
+  xenstore-watch -n 2 "$device_model/command"
+  cmd="$(xenstore-read $device_model/command)"
+  if [ "$cmd" != "pci-ins" ] && [ "$cmd" != "pci-rem" ]; then
+    continue
+  fi
+
+  para="$(xenstore-read "$device_model/parameter")"
+
+  # backend pci device id like 0000:01:02.3
+  dev="$(printf %s "$para" | cut -b 1-12)"
+
+  qdev_id="xen-pci-pt_$(printf %s "$dev" | tr : -)"
+
+  # handle pci remove request
+  if [ "$cmd" = "pci-rem" ]; then
+    qmp_req "$(cat <<EOC
+{"execute": "device_del", "arguments": {"id": "$qdev_id"}}
+EOC
+      )" > /dev/null
+    xenstore-write "$device_model/state" "pci-removed"
+    continue
+  fi
+
+  # handle pci add request
+  be="$(xenstore-read device/pci/0/backend)"
+  devs="$(xenstore-read $be/num_devs)"
+
+  dev_n=
+  for i in $(seq 0 $(( devs - 1 ))); do
+    if [ "$dev" = "$(xenstore-read "$be/dev-$i" | sed 's/\.0\([0-9]\)$/.\1/')" ]; then
+      dev_n=$i
+      break
+    fi
+  done
+
+  if [ -z "$dev_n" ]; then
+    echo "could not find backend entry for device $dev"
+    exit 1
+  fi
+
+  vdev="$(xenstore-read "$be/vdev-$dev_n")"
+
+  addr_arg=
+  vdevfn="$(xenstore-read "$be/vdevfn-$dev_n" || true)"
+  if [ -n "$vdevfn" ]; then
+    addr_arg="\"addr\": \"$(( ($vdevfn >> 3) & 0x1f )).$(( $vdevfn & 0x07 ))\", "
+  fi
+
+  permissive=false
+  if xenstore-read "$be/opts-$dev_n" | grep -q '\<permissive=1\>'; then
+    permissive=true
+  fi
+
+  qmp_req "$(cat <<EOC
+  {"execute": "device_add", "arguments": {"driver": "xen-pci-passthrough", "id": "$qdev_id", "hostaddr": "$vdev",$addr_arg "permissive": $permissive}}
+EOC
+  )" > /dev/null
+
+  # XXX: use jq?
+  slot_func="$(qmp_req '{"execute": "query-pci"}' | sed 's/"qdev_id"/\n\0/g' | sed -n '/"qdev_id": "'"$qdev_id"'"/{s/.*"slot": \([0-9]\+\),.*"function": \([0-9]\+\),.*/\1,\2/;p}')"
+
+  slot="$(printf %s "$slot_func" | cut -d , -f 1)"
+  func="$(printf %s "$slot_func" | cut -d , -f 2)"
+
+  vdevfn="$(( (($slot & 0x1f) << 3) | ($func & 0x07) ))"
+
+  xenstore-write "$device_model/parameter" "$(printf '0x%02x' "$vdevfn")"
+  xenstore-write "$device_model/state" "pci-inserted"
+done
+) &
 
 while true; do
   sleep 1d
